AMP-16873: Only run `amp-build` when `pom.xml` exists in the CWD.
git-svn-id: http://svn.dgfoundation.org/amp/branches/AMP_2_12_RELEASE@30631 9e8d75aa-d0cb-44a9-8341-a4b8ba1a38b4

diff --git a/amp-deployer/roles/amp/templates/amp-build.sh.j2 b/amp-deployer/roles/amp/templates/amp-build.sh.j2
--- a/amp-deployer/roles/amp/templates/amp-build.sh.j2
+++ b/amp-deployer/roles/amp/templates/amp-build.sh.j2
@@ -3,6 +3,12 @@
 ## {{ ansible_managed }}
 ## TODO: Use variables.
 
+if [ ! -f pom.xml ]
+then
+  echo "Not a maven project, `pom.xml` not found!"
+  exit 2
+fi
+
 mvn clean \
     generate-resources \
     process-resources \
