AMP-16873: Fix `amp-build` warning.
git-svn-id: http://svn.dgfoundation.org/amp/branches/AMP_2_12_RELEASE@30632 9e8d75aa-d0cb-44a9-8341-a4b8ba1a38b4

diff --git a/amp-deployer/roles/amp/templates/amp-build.sh.j2 b/amp-deployer/roles/amp/templates/amp-build.sh.j2
--- a/amp-deployer/roles/amp/templates/amp-build.sh.j2
+++ b/amp-deployer/roles/amp/templates/amp-build.sh.j2
@@ -5,8 +5,8 @@
 
 if [ ! -f pom.xml ]
 then
-  echo "Not a maven project, `pom.xml` not found!"
-  exit 2
+  echo "Not a maven project, 'pom.xml' not found!"
+  exit 1
 fi
 
 mvn clean \
